/**
 * Base de données de plantes d'intérieur disponibles pour l'ajout manuel
 */

interface PlantEntry {
  name: string;
  species: string;
  wateringFrequency: number;
  light: string;
  temperature: string;
  careNotes: string;
}

export const plantDatabase: PlantEntry[] = [
  // Variétés de tomates
  {
    name: "Tomate Coeur de Boeuf",
    species: "Solanum lycopersicum 'Cuore di Bue'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement sans mouiller le feuillage. Installez des tuteurs pour supporter le poids des fruits. Besoin de beaucoup de soleil pour des fruits savoureux.",
  },
  {
    name: "Tomate Cerise",
    species: "Solanum lycopersicum var. cerasiforme",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement mais sans excès. Très productive et facile à cultiver. Idéale pour les balcons et petits espaces.",
  },
  {
    name: "Tomate Noire de Crimée",
    species: "Solanum lycopersicum 'Black Krim'",
    wateringFrequency: 2,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement et généreusement. Variété ancienne à la saveur incomparable. Supporte bien la chaleur.",
  },
  {
    name: "Tomate Green Zebra",
    species: "Solanum lycopersicum 'Green Zebra'",
    wateringFrequency: 2,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement et de manière constante. Supporte bien les conditions chaudes. Fruits verts striés, saveur légèrement acidulée.",
  },
  {
    name: "Tomate San Marzano",
    species: "Solanum lycopersicum 'San Marzano'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-32°C",
    careNotes: "Arrosez régulièrement mais sans excès. Idéale pour les sauces et conserves. Nécessite un tuteurage solide.",
  },
  {
    name: "Tomate Ananas",
    species: "Solanum lycopersicum 'Pineapple'",
    wateringFrequency: 2,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement et généreusement. Gros fruits bicolores jaune-orangé marbrés de rouge. Saveur douce et fruitée.",
  },
  {
    name: "Tomate Roma",
    species: "Solanum lycopersicum 'Roma VF'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez sans mouiller le feuillage. Variété déterminée compacte. Idéale pour les sauces et la mise en conserve.",
  },
  {
    name: "Tomate Marmande",
    species: "Solanum lycopersicum 'Marmande'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "16-30°C",
    careNotes: "Arrosez régulièrement. Variété française précoce et productive. Fruits côtelés à la saveur équilibrée.",
  },
  {
    name: "Tomate Brandywine",
    species: "Solanum lycopersicum 'Brandywine'",
    wateringFrequency: 2,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez généreusement. Variété ancienne à gros fruits. Feuillage de type pomme de terre, saveur exceptionnelle.",
  },
  {
    name: "Tomate Beefsteak",
    species: "Solanum lycopersicum 'Beefsteak'",
    wateringFrequency: 2,
    light: "Directe",
    temperature: "18-32°C",
    careNotes: "Arrosez régulièrement et abondamment. Très gros fruits charnues. Idéale pour les sandwichs et hamburgers.",
  },
  {
    name: "Tomate Cornue des Andes",
    species: "Solanum lycopersicum 'Cornue des Andes'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement. Fruits allongés en forme de corne. Peu de graines, chair ferme et saveur douce.",
  },
  {
    name: "Tomate Raisin Vert",
    species: "Solanum lycopersicum 'Green Grape'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez sans excès. Petits fruits verts de la taille d'un raisin. Saveur délicieuse et sucrée.",
  },
  {
    name: "Tomate Petit Moineau",
    species: "Solanum lycopersicum 'Petit Moineau'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement. Très petites tomates cerises rouges. Extrêmement productive et résistante.",
  },
  {
    name: "Tomate Yellow Pear",
    species: "Solanum lycopersicum 'Yellow Pear'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement. Petits fruits jaunes en forme de poire. Idéale pour les salades et la décoration.",
  },
  {
    name: "Tomate Gardener's Delight",
    species: "Solanum lycopersicum 'Gardener's Delight'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "16-30°C",
    careNotes: "Arrosez régulièrement. Tomate cerise très appréciée des jardiniers. Saveur sucrée et production abondante.",
  },
  {
    name: "Tomate Tigerella",
    species: "Solanum lycopersicum 'Tigerella'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement. Fruits rouges avec rayures jaunes-orangées. Goût acidulé et rafraichissant.",
  },
  {
    name: "Tomate Rose de Berne",
    species: "Solanum lycopersicum 'Rose de Berne'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez sans excès. Variété ancienne suisse à fruits roses. Chair juteuse et peau fine, saveur douce et fruitée.",
  },
  {
    name: "Tomate Indigo Rose",
    species: "Solanum lycopersicum 'Indigo Rose'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement. Fruits pourpres-noirs riches en anthocyanes. Saveur équilibrée et riche en antioxydants.",
  },
  {
    name: "Tomate Moneymaker",
    species: "Solanum lycopersicum 'Moneymaker'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez modérément. Variété anglaise fiable et productive. Fruits ronds de taille moyenne, croissance vigoureuse.",
  },
  {
    name: "Tomate Stupice",
    species: "Solanum lycopersicum 'Stupice'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "16-28°C",
    careNotes: "Arrosez régulièrement. Variété très précoce originaire de Tchéquie. Idéale pour les climats frais et les saisons courtes.",
  },
  {
    name: "Tomate Principe Borghese",
    species: "Solanum lycopersicum 'Principe Borghese'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-32°C",
    careNotes: "Arrosez sans excès. Variété italienne traditionnelle pour séchage. Petits fruits charnus avec peu de graines.",
  },
  {
    name: "Tomate Black Cherry",
    species: "Solanum lycopersicum 'Black Cherry'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez modérément. Tomate cerise de couleur pourpre-noir. Saveur complexe et riche, production abondante.",
  },
  {
    name: "Tomate Alicante",
    species: "Solanum lycopersicum 'Alicante'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement. Variété britannique classique. Fruits ronds rouges de bonne conservation, saveur équilibrée.",
  },
  {
    name: "Tomate Saint Pierre",
    species: "Solanum lycopersicum 'Saint Pierre'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez régulièrement. Variété française traditionnelle. Fruits ronds, rouges et fermes, idéaux pour les conserves.",
  },
  {
    name: "Tomate Sungold",
    species: "Solanum lycopersicum 'Sungold'",
    wateringFrequency: 3,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez modérément. Tomate cerise orange très sucrée. Incroyable saveur fruitée, souvent considérée comme la plus sucrée.",
  },
  {
    name: "Vase d'argent",
    species: "Aechmea fasciata",
    wateringFrequency: 7,
    light: "Indirecte brillante",
    temperature: "18-24°C",
    careNotes: "Versez l'eau au centre du rosette. Tolère l'oubli d'arrosage. Préfère une lumière vive sans soleil direct.",
  },
  {
    name: "Capillaire",
    species: "Adiantum raddianum",
    wateringFrequency: 3,
    light: "Indirecte",
    temperature: "18-24°C",
    careNotes: "Maintenez le substrat constamment humide. Placez dans un endroit lumineux sans soleil direct. Vaporisez régulièrement pour maintenir une bonne humidité.",
  },
  {
    name: "Aglaonéma",
    species: "Aglaonema commutatum",
    wateringFrequency: 7,
    light: "Faible à modérée",
    temperature: "18-27°C",
    careNotes: "Arrosez quand le dessus du terreau est sec. Tolère la faible luminosité. Idéale pour les espaces avec peu de lumière naturelle.",
  },
  {
    name: "Oreille d'éléphant",
    species: "Alocasia amazonica",
    wateringFrequency: 5,
    light: "Indirecte brillante",
    temperature: "18-30°C",
    careNotes: "Maintenez le substrat légèrement humide. Placez dans un endroit lumineux sans soleil direct. Apprécie l'humidité ambiante élevée.",
  },
  {
    name: "Anthurium",
    species: "Anthurium andraeanum",
    wateringFrequency: 7,
    light: "Indirecte brillante",
    temperature: "18-27°C",
    careNotes: "Laissez sécher légèrement entre les arrosages. Apprécie une lumière vive sans soleil direct. Vaporisez le feuillage régulièrement.",
  },
  {
    name: "Pin de Norfolk",
    species: "Araucaria heterophylla",
    wateringFrequency: 7,
    light: "Indirecte brillante",
    temperature: "13-24°C",
    careNotes: "Arrosez modérément, laissez sécher entre les arrosages. Évitez le soleil direct qui peut brûler les branches. Préfère les températures fraîches.",
  },
  {
    name: "Plante de fer",
    species: "Aspidistra elatior",
    wateringFrequency: 10,
    light: "Faible à modérée",
    temperature: "10-24°C",
    careNotes: "Extrêmement résistante, supporte la négligence. Tolère très bien l'ombre. Arrosez sobrement, laissez sécher entre les arrosages.",
  },
  {
    name: "Fougère nid d'oiseau",
    species: "Asplenium nidus",
    wateringFrequency: 5,
    light: "Indirecte",
    temperature: "18-27°C",
    careNotes: "Maintenez le substrat constamment humide. Apprécie l'humidité ambiante. Ne laissez jamais sécher complètement.",
  },
  {
    name: "Pied d'éléphant",
    species: "Beaucarnea recurvata",
    wateringFrequency: 14,
    light: "Directe",
    temperature: "15-30°C",
    careNotes: "Extrêmement résistante à la sécheresse. Arrosez peu et laissez sécher entre les arrosages. Tolère le soleil direct.",
  },
  {
    name: "Bégonia royal",
    species: "Begonia rex",
    wateringFrequency: 7,
    light: "Indirecte",
    temperature: "18-24°C",
    careNotes: "Arrosez quand la surface du terreau est sèche. Évitez de mouiller les feuilles. Apprécie l'humidité ambiante sans arrosage direct.",
  },
  {
    name: "Caladium",
    species: "Caladium bicolor",
    wateringFrequency: 3,
    light: "Indirecte",
    temperature: "18-30°C",
    careNotes: "Maintenez le substrat humide. Apprécie la chaleur et l'humidité. Évitez les courants d'air froid.",
  },
  {
    name: "Plante paon",
    species: "Calathea makoyana",
    wateringFrequency: 5,
    light: "Indirecte faible",
    temperature: "18-24°C",
    careNotes: "Maintenez le substrat légèrement humide. Sensible au chlore, utilisez de l'eau filtrée. Apprécie l'humidité ambiante élevée.",
  },
  {
    name: "Palmier nain",
    species: "Chamaedorea elegans",
    wateringFrequency: 7,
    light: "Indirecte",
    temperature: "18-24°C",
    careNotes: "Arrosez quand le dessus du terreau est sec. Tolère l'ombre. Vaporisez régulièrement pour prévenir les araignées rouges.",
  },
  {
    name: "Plante araignée",
    species: "Chlorophytum comosum",
    wateringFrequency: 7,
    light: "Indirecte à directe",
    temperature: "13-27°C",
    careNotes: "Arrosez quand le terreau est sec. Très résistante et facile à entretenir. Produit des plantules faciles à propager.",
  },
  {
    name: "Vigne d'intérieur",
    species: "Cissus rhombifolia",
    wateringFrequency: 7,
    light: "Indirecte brillante",
    temperature: "15-27°C",
    careNotes: "Arrosez quand la surface du terreau est sèche. Offrez un support pour grimper. Apprécie l'humidité ambiante.",
  },
  {
    name: "Clivia",
    species: "Clivia miniata",
    wateringFrequency: 10,
    light: "Indirecte",
    temperature: "15-24°C",
    careNotes: "Laissez sécher entre les arrosages. Période de repos en hiver nécessaire pour la floraison. Réduisez l'arrosage en hiver.",
  },
  {
    name: "Croton",
    species: "Codiaeum variegatum",
    wateringFrequency: 5,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Maintenez le substrat légèrement humide. Les couleurs sont plus vives avec plus de lumière. Vaporisez régulièrement.",
  },
  {
    name: "Plante de jade",
    species: "Crassula ovata",
    wateringFrequency: 14,
    light: "Directe",
    temperature: "15-24°C",
    careNotes: "Arrosez rarement, laissez sécher complètement entre les arrosages. Placez en plein soleil. Très facile à entretenir.",
  },
  {
    name: "Cyclamen",
    species: "Cyclamen persicum",
    wateringFrequency: 5,
    light: "Indirecte brillante",
    temperature: "10-18°C",
    careNotes: "Arrosez par le bas pour éviter de mouiller le collet. Préfère les températures fraîches. Entre en dormance l'été.",
  },
  {
    name: "Dieffenbachia",
    species: "Dieffenbachia seguine",
    wateringFrequency: 7,
    light: "Indirecte",
    temperature: "18-27°C",
    careNotes: "Arrosez quand la surface du terreau est sèche. Attention, toutes les parties sont toxiques si ingérées. Tolère l'ombre.",
  },
  {
    name: "Dragonnier",
    species: "Dracaena fragrans",
    wateringFrequency: 10,
    light: "Indirecte",
    temperature: "18-24°C",
    careNotes: "Laissez sécher entre les arrosages. Tolère une large gamme de conditions. Sensible au fluor, utilisez de l'eau filtrée.",
  },
  {
    name: "Pothos",
    species: "Epipremnum aureum",
    wateringFrequency: 7,
    light: "Faible à brillante",
    temperature: "15-30°C",
    careNotes: "Arrosez quand le terreau est sec. Extrêmement adaptable et facile à cultiver. Peut être taillé pour encourager la ramification.",
  },
  {
    name: "Figuier pleureur",
    species: "Ficus benjamina",
    wateringFrequency: 7,
    light: "Indirecte brillante",
    temperature: "18-24°C",
    careNotes: "Arrosez quand la surface du terreau est sèche. N'aime pas être déplacé. Sensible aux courants d'air.",
  },
  {
    name: "Caoutchouc",
    species: "Ficus elastica",
    wateringFrequency: 10,
    light: "Indirecte brillante",
    temperature: "18-30°C",
    careNotes: "Laissez sécher entre les arrosages. Essuyez les feuilles régulièrement pour enlever la poussière. Peut atteindre plusieurs mètres.",
  },
  {
    name: "Plante mosaïque",
    species: "Fittonia albivenis",
    wateringFrequency: 3,
    light: "Indirecte faible",
    temperature: "18-27°C",
    careNotes: "Maintenez le substrat constamment humide. Apprécie l'humidité ambiante élevée. Parfaite pour terrariums.",
  },
  {
    name: "Lierre",
    species: "Hedera helix",
    wateringFrequency: 7,
    light: "Indirecte",
    temperature: "10-21°C",
    careNotes: "Arrosez modérément, laissez sécher entre les arrosages. Préfère les températures fraîches. Vaporisez régulièrement.",
  },
  {
    name: "Fleur de porcelaine",
    species: "Hoya carnosa",
    wateringFrequency: 10,
    light: "Indirecte brillante",
    temperature: "18-24°C",
    careNotes: "Laissez sécher entre les arrosages. Ne coupez pas les tiges florales après la floraison. Apprécie d'être à l'étroit dans son pot.",
  },
  {
    name: "Kalanchoé",
    species: "Kalanchoe blossfeldiana",
    wateringFrequency: 10,
    light: "Directe",
    temperature: "15-24°C",
    careNotes: "Arrosez uniquement quand le substrat est sec. Supporte bien la sécheresse. Nécessite des jours courts pour fleurir.",
  },
  {
    name: "Plante qui prie",
    species: "Maranta leuconeura",
    wateringFrequency: 5,
    light: "Indirecte faible",
    temperature: "18-24°C",
    careNotes: "Maintenez le substrat légèrement humide. Sensible au chlore, utilisez de l'eau filtrée. Feuilles qui se replient la nuit.",
  },
  {
    name: "Plante à trous",
    species: "Monstera deliciosa",
    wateringFrequency: 7,
    light: "Indirecte brillante",
    temperature: "18-30°C",
    careNotes: "Arrosez quand le terreau commence à sécher. Apprécie un tuteur pour grimper. Les feuilles développent des trous avec l'âge.",
  },
  {
    name: "Fougère de Boston",
    species: "Nephrolepis exaltata",
    wateringFrequency: 3,
    light: "Indirecte",
    temperature: "18-24°C",
    careNotes: "Maintenez le substrat constamment humide. Vaporisez régulièrement. Ne laissez jamais sécher complètement.",
  },
  {
    name: "Peperomia",
    species: "Peperomia obtusifolia",
    wateringFrequency: 7,
    light: "Indirecte",
    temperature: "18-24°C",
    careNotes: "Arrosez quand la surface du terreau est sèche. Feuilles succulentes qui stockent l'eau. Idéal pour petits espaces.",
  },
  {
    name: "Philodendron",
    species: "Philodendron scandens",
    wateringFrequency: 7,
    light: "Indirecte",
    temperature: "18-27°C",
    careNotes: "Arrosez quand la surface du terreau est sèche. Très facile à cultiver. Peut grimper ou retomber selon vos préférences.",
  },
  {
    name: "Plante à monnaie chinoise",
    species: "Pilea peperomioides",
    wateringFrequency: 7,
    light: "Indirecte brillante",
    temperature: "15-24°C",
    careNotes: "Arrosez quand le terreau commence à sécher. Tournez régulièrement pour une croissance uniforme. Produit facilement des rejets.",
  },
  {
    name: "Langue de belle-mère",
    species: "Sansevieria trifasciata",
    wateringFrequency: 14,
    light: "Faible à directe",
    temperature: "15-30°C",
    careNotes: "Arrosez très peu, laissez sécher complètement entre les arrosages. Extrêmement résistante, presque indestructible. Purifie l'air.",
  },
  {
    name: "Fleur de lune",
    species: "Spathiphyllum wallisii",
    wateringFrequency: 7,
    light: "Indirecte faible",
    temperature: "18-27°C",
    careNotes: "Maintenez le substrat légèrement humide. S'affaisse quand elle a besoin d'eau. Fleurit même avec peu de lumière.",
  },
  {
    name: "Oiseau de paradis",
    species: "Strelitzia reginae",
    wateringFrequency: 7,
    light: "Directe",
    temperature: "18-30°C",
    careNotes: "Arrosez quand la surface du terreau est sèche. Nécessite beaucoup de lumière pour fleurir. Plante imposante et spectaculaire.",
  },
  {
    name: "Syngonium",
    species: "Syngonium podophyllum",
    wateringFrequency: 7,
    light: "Indirecte",
    temperature: "18-27°C",
    careNotes: "Arrosez quand la surface du terreau est sèche. Les feuilles changent de forme avec l'âge. Peut grimper avec un support.",
  },
  {
    name: "Misère",
    species: "Tradescantia zebrina",
    wateringFrequency: 5,
    light: "Indirecte brillante",
    temperature: "15-27°C",
    careNotes: "Maintenez le substrat légèrement humide. Croissance rapide et facile à propager. Couleurs plus vives avec plus de lumière.",
  },
  {
    name: "Yucca",
    species: "Yucca elephantipes",
    wateringFrequency: 14,
    light: "Directe",
    temperature: "15-30°C",
    careNotes: "Arrosez très peu, laissez sécher complètement entre les arrosages. Très résistant à la sécheresse. Préfère le plein soleil.",
  },
  {
    name: "Plante ZZ",
    species: "Zamioculcas zamiifolia",
    wateringFrequency: 14,
    light: "Faible à brillante",
    temperature: "15-30°C",
    careNotes: "Arrosez très peu, laissez sécher complètement entre les arrosages. Extrêmement résistante à la négligence. Tolère très bien l'ombre.",
  },
];

export function searchPlants(query: string): PlantEntry[] {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return [];
  
  console.log("Recherche de plantes avec requête:", query);
  
  const results = plantDatabase.filter(plant => 
    plant.name.toLowerCase().includes(normalizedQuery) ||
    plant.species.toLowerCase().includes(normalizedQuery)
  );
  
  console.log(`${results.length} plantes trouvées pour "${query}"`);
  return results;
}

export function getPlantByName(name: string): PlantEntry | undefined {
  const normalizedName = name.toLowerCase().trim();
  return plantDatabase.find(plant => 
    plant.name.toLowerCase() === normalizedName ||
    plant.species.toLowerCase() === normalizedName
  );
}